steps:
- name: Checkout code
  uses: actions/checkout@v3
  with:
    submodules: recursive
  args: [ 'build', '-t', 'us.gcr.io/$PROJECT_ID/ece461_project2:latest', '.' ]

images: [eu.gcr.io/$PROJECT_ID/ece461_project2:latest]
