steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['submodule', 'update', '--init', '--recursive']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
    'build', 
    '-t', 'us.gcr.io/$PROJECT_ID/package-registry:latest', 
    '--cache-from', 'us.gcr.io/$PROJECT_ID/package-registry:latest',
    '.' 
  ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 
#     'run', 
#     '-p', '8080:80', 
#     'us.gcr.io/$PROJECT_ID/package-registry:latest',
#   ]
images: [us.gcr.io/$PROJECT_ID/package-registry:latest]
