version: "3"

services:
  project2:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
     
    image: ece461_project2:latest

    command: bash -c "./run" 

    volumes:
      - ./PackageRegistry:/home/project2/PackageRegistry
    # env_file:
    #   - .env
      