version: "3"

services:
  project2:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build-env
     
    image: ece461_project2:latest

    command: bash -c "cd /home/project2 && ./run" 

    volumes:
      - ./PackageRegistry:/home/project2/PackageRegistry
      - ./PackageRegistry.Tests:/home/project2/PackageRegistry.Tests
      - ./run:/home/project2/run
    env_file:
      - .env
      