# This workflow will test the package rater

name: Test rater

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_rater:
    name: Test rater
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Test rater
#       working-directory: ECE461-Project-Part1-Handoff-CLI
      run: 
        cd ECE461-Project-Part1-Handoff-CLI
        ls
    - name: Checkout sub
      uses: actions/checkout@v3
      
